version: '2'
services:  
  zabbix:
    build: .         
    container_name: ZabbixServer
    volumes:
      - .\Banco:/var/lib/mysql
      - .\zabbix_config:/etc/zabbix
    ports:
      - "80:80"
      - "10051:10051"
   